# import relavant libraries

In [1]:
import numpy as np
import pandas as pd

# load the data


In [2]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed.head(28)

Reason_type_1  Reason_type_2  Reason_type_3  Reason_type_4        Date   
0           False          False          False           True  2015-07-07  \
1           False          False          False          False  2015-07-14   
2           False          False          False           True  2015-07-15   
3            True          False          False          False  2015-07-16   
4           False          False          False           True  2015-07-23   
5           False          False          False           True  2015-07-10   
6           False          False          False           True  2015-07-17   
7           False          False          False           True  2015-07-24   
8           False          False           True          False  2015-07-06   
9           False          False          False           True  2015-07-13   
10           True          False          False          False  2015-07-20   
11           True          False          False          False  2015-07-14   
12           True          False          False          False  2015-07-15   
13           True          False          False          False  2015-07-15   
14          False          False          False           True  2015-07-15   
15           True          False          False          False  2015-07-17   
16          False          False          False           True  2015-07-17   
17          False          False           True          False  2015-07-27   
18           True          False          False          False  2015-07-30   
19          False          False          False           True  2015-08-05   
20           True          False          False          False  2015-08-12   
21           True          False          False          False  2015-08-03   
22           True          False          False          False  2015-08-10   
23          False          False          False           True  2015-08-14   
24          False          False           True          False  2015-08-17   
25          False          False          False           True  2015-08-24   
26          False          False          False           True  2015-08-04   
27          False          False          False           True  2015-08-12   

    Transportation Expense  Distance to Work  Age  Daily Work Load Average   
0                      289                36   33                  239.554  \
1                      118                13   50                  239.554   
2                      179                51   38                  239.554   
3                      279                 5   39                  239.554   
4                      289                36   33                  239.554   
5                      179                51   38                  239.554   
6                      361                52   28                  239.554   
7                      260                50   36                  239.554   
8                      155                12   34                  239.554   
9                      235                11   37                  239.554   
10                     260                50   36                  239.554   
11                     260                50   36                  239.554   
12                     260                50   36                  239.554   
13                     179                51   38                  239.554   
14                     179                51   38                  239.554   
15                     246                25   41                  239.554   
16                     179                51   38                  239.554   
17                     179                51   38                  239.554   
18                     189                29   33                  239.554   
19                     248                25   47                  205.917   
20                     330                16   28                  205.917   
21                     17

# create the targets

In [4]:
median = data_preprocessed['Absenteeism Time in Hours'].median()

In [5]:
median

3.0

In [6]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours']>median,1,0)

In [7]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [8]:
data_preprocessed['Excessive Absenteeism']=targets

In [9]:
data_preprocessed.head()

Reason_type_1  Reason_type_2  Reason_type_3  Reason_type_4        Date   
0          False          False          False           True  2015-07-07  \
1          False          False          False          False  2015-07-14   
2          False          False          False           True  2015-07-15   
3           True          False          False          False  2015-07-16   
4          False          False          False           True  2015-07-23   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average   
0                     289                36   33                  239.554  \
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours   
0               30          0         2     1                          4  \
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Month Values  Day of the week  Excessive Absenteeism  
0             7                1                      1  
1             7                1                      0  
2             7                2                      0  
3             7                3                      1  
4             7                3                      0

In [10]:
targets.sum()

319

In [11]:
targets.shape[0]

700

In [12]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [13]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Day of the week','Daily Work Load Average','Distance to Work'],axis=1)

In [14]:
data_with_targets is data_preprocessed

False

In [15]:
data_with_targets.head()

Reason_type_1  Reason_type_2  Reason_type_3  Reason_type_4        Date   
0          False          False          False           True  2015-07-07  \
1          False          False          False          False  2015-07-14   
2          False          False          False           True  2015-07-15   
3           True          False          False          False  2015-07-16   
4          False          False          False           True  2015-07-23   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets   
0                     289   33               30          0         2     1  \
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   

   Month Values  Excessive Absenteeism  
0             7                      1  
1             7                      0  
2             7                      0  
3             7                      1  
4             7                      0

# select inputs for the regression

In [16]:
data_with_targets.shape

(700, 13)

In [17]:
data_with_targets = data_with_targets.drop(['Date'],axis=1)

In [18]:
data_with_targets.shape

(700, 12)

In [19]:
data_with_targets.iloc[:,0:14]

Reason_type_1  Reason_type_2  Reason_type_3  Reason_type_4   
0            False          False          False           True  \
1            False          False          False          False   
2            False          False          False           True   
3             True          False          False          False   
4            False          False          False           True   
..             ...            ...            ...            ...   
695           True          False          False          False   
696           True          False          False          False   
697           True          False          False          False   
698          False          False          False           True   
699          False          False          False           True   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets   
0                       289   33               30          0         2     1  \
1                       118   50               31          0         1     0   
2                       179   38               31          0         0     0   
3                       279   39               24          0         2     0   
4                       289   33               30          0         2     1   
..                      ...  ...              ...        ...       ...   ...   
695                     179   40               22          1         2     0   
696                     225   28               24          0         1     2   
697                     330   28               25          1         0     0   
698                     235   32               25          1         0     0   
699                     291   40               25          0         1     1   

     Month Values  Excessive Absenteeism  
0               7                      1  
1               7                      0  
2               7                      0  
3               7                      1  
4               7                      0  
..            ...                    ...  
695             5                      1  
696             5                      0  
697             5                      1  
698             5                      0  
699             5                      0  

[700 rows x 12 columns]

In [20]:
data_with_targets.iloc[:,:-1]

Reason_type_1  Reason_type_2  Reason_type_3  Reason_type_4   
0            False          False          False           True  \
1            False          False          False          False   
2            False          False          False           True   
3             True          False          False          False   
4            False          False          False           True   
..             ...            ...            ...            ...   
695           True          False          False          False   
696           True          False          False          False   
697           True          False          False          False   
698          False          False          False           True   
699          False          False          False           True   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets   
0                       289   33               30          0         2     1  \
1                       118   50               31          0         1     0   
2                       179   38               31          0         0     0   
3                       279   39               24          0         2     0   
4                       289   33               30          0         2     1   
..                      ...  ...              ...        ...       ...   ...   
695                     179   40               22          1         2     0   
696                     225   28               24          0         1     2   
697                     330   28               25          1         0     0   
698                     235   32               25          1         0     0   
699                     291   40               25          0         1     1   

     Month Values  
0               7  
1               7  
2               7  
3               7  
4               7  
..            ...  
695             5  
696             5  
697             5  
698             5  
699             5  

[700 rows x 11 columns]

In [21]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

In [22]:
unscaled_inputs.head()

Reason_type_1  Reason_type_2  Reason_type_3  Reason_type_4   
0          False          False          False           True  \
1          False          False          False          False   
2          False          False          False           True   
3           True          False          False          False   
4          False          False          False           True   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets   
0                     289   33               30          0         2     1  \
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   

   Month Values  
0             7  
1             7  
2             7  
3             7  
4             7

In [23]:
unscaled_inputs.shape

(700, 11)

# standardize the data

In [24]:
from sklearn.preprocessing import StandardScaler
absenteeism_scaler = StandardScaler()

In [25]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler


class CustomScaler(BaseEstimator,TransformerMixin): 
    
    def __init__(self,columns):
        self.scaler = StandardScaler()
        self.columns = columns
        self.mean_ = None
        self.var_ = None
 
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.array(np.mean(X[self.columns]))
        self.var_ = np.array(np.var(X[self.columns]))
        return self
 
    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), 
        columns=self.columns)
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]


In [26]:
unscaled_inputs.columns.values

array(['Reason_type_1', 'Reason_type_2', 'Reason_type_3', 'Reason_type_4',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month Values'], dtype=object)

In [27]:
unscaled_inputs.columns.values

array(['Reason_type_1', 'Reason_type_2', 'Reason_type_3', 'Reason_type_4',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month Values'], dtype=object)

In [28]:
#columns_to_scale = ['Transportation Expense', 'Distance to Work', 'Age','Daily Work Load Average', 'Body Mass Index',
#'Children', 'Pets', 'Month Values', 'Day of the week']

columns_to_ommit = ['Reason_type_1', 'Reason_type_2', 'Reason_type_3', 'Reason_type_4','Education']

In [29]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_ommit]

In [30]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [31]:
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Transportation Expense', 'Age', 'Body Mass Index',
                      'Children', 'Pets', 'Month Values'])

In [32]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [33]:
scaled_inputs

Reason_type_1  Reason_type_2  Reason_type_3  Reason_type_4   
0            False          False          False           True  \
1            False          False          False          False   
2            False          False          False           True   
3             True          False          False          False   
4            False          False          False           True   
..             ...            ...            ...            ...   
695           True          False          False          False   
696           True          False          False          False   
697           True          False          False          False   
698          False          False          False           True   
699          False          False          False           True   

     Transportation Expense       Age  Body Mass Index  Education  Children   
0                  1.005844 -0.536062         0.767431          0  0.880469  \
1                 -1.574681  2.130803         1.002633          0 -0.019280   
2                 -0.654143  0.248310         1.002633          0 -0.919030   
3                  0.854936  0.405184        -0.643782          0  0.880469   
4                  1.005844 -0.536062         0.767431          0  0.880469   
..                      ...       ...              ...        ...       ...   
695               -0.654143  0.562059        -1.114186          1  0.880469   
696                0.040034 -1.320435        -0.643782          0 -0.019280   
697                1.624567 -1.320435        -0.408580          1 -0.919030   
698                0.190942 -0.692937        -0.408580          1 -0.919030   
699                1.036026  0.562059        -0.408580          0 -0.019280   

         Pets  Month Values  
0    0.268487      0.182726  
1   -0.589690      0.182726  
2   -0.589690      0.182726  
3   -0.589690      0.182726  
4    0.268487      0.182726  
..        ...           ...  
695 -0.589690     -0.388293  
696  1.126663     -0.388293  
697 -0.589690     -0.388293  
698 -0.589690     -0.388293  
699  0.268487     -0.388293  

[700 rows x 11 columns]

In [34]:
scaled_inputs.shape

(700, 11)

# split the data into train & test and shuffle

### import the relevant module

In [35]:
from sklearn.model_selection import train_test_split

### split

In [36]:
train_test_split(scaled_inputs, targets)

[     Reason_type_1  Reason_type_2  Reason_type_3  Reason_type_4   
 70           False          False          False           True  \
 109          False          False          False           True   
 203          False          False          False          False   
 139           True          False          False          False   
 635           True          False          False          False   
 ..             ...            ...            ...            ...   
 694          False          False          False           True   
 556          False          False          False           True   
 520          False          False          False           True   
 34           False          False          False           True   
 373          False          False          False           True   
 
      Transportation Expense       Age  Body Mass Index  Education  Children   
 70                 0.387122  1.660180         1.237836          0  0.880469  \
 109                2.

In [37]:
x_train,x_test,y_train,y_test = train_test_split(scaled_inputs,targets,train_size=0.8,random_state =20)

In [38]:
print(x_train.shape,y_train.shape)

(560, 11) (560,)


In [39]:
print(x_test.shape,y_test.shape)

(140, 11) (140,)


# logistic regression with sklearn

In [40]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

# training the model

In [41]:
reg = LogisticRegression()

In [42]:
reg.fit(x_train,y_train)

LogisticRegression()

In [43]:
reg.score(x_train,y_train)

0.7732142857142857

# manually check the accuracy

In [44]:
model_outputs = reg.predict(x_train)

In [45]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [46]:
np.sum((model_outputs == y_train))

433

In [47]:
model_outputs.shape[0]

560

In [48]:
accuracy = np.sum((model_outputs == y_train)) / model_outputs.shape[0]

In [49]:
accuracy

0.7732142857142857

# finding the intercept and coefficients


In [50]:
reg.intercept_

array([-1.6474549])

In [51]:
reg.coef_

array([[ 2.80019733,  0.95188356,  3.11555338,  0.83900082,  0.60528415,
        -0.16989096,  0.27981088, -0.21053312,  0.34826214, -0.27739602,
         0.1589299 ]])

In [52]:
scaled_inputs.columns.values

array(['Reason_type_1', 'Reason_type_2', 'Reason_type_3', 'Reason_type_4',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month Values'], dtype=object)

In [53]:
unscaled_inputs.columns.values

array(['Reason_type_1', 'Reason_type_2', 'Reason_type_3', 'Reason_type_4',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month Values'], dtype=object)

In [54]:
feature_name = unscaled_inputs.columns.values

In [55]:
summary_table = pd.DataFrame(columns=['Feature name'],data = feature_name)

In [56]:
summary_table['coefficient'] = np.transpose(reg.coef_)
summary_table

Feature name  coefficient
0            Reason_type_1     2.800197
1            Reason_type_2     0.951884
2            Reason_type_3     3.115553
3            Reason_type_4     0.839001
4   Transportation Expense     0.605284
5                      Age    -0.169891
6          Body Mass Index     0.279811
7                Education    -0.210533
8                 Children     0.348262
9                     Pets    -0.277396
10            Month Values     0.158930

In [57]:
summary_table.index = summary_table.index + 1

In [58]:
summary_table.loc[0] = ['Intercept',reg.intercept_[0]]
summary_table = summary_table.sort_index()

In [59]:
summary_table

Feature name  coefficient
0                Intercept    -1.647455
1            Reason_type_1     2.800197
2            Reason_type_2     0.951884
3            Reason_type_3     3.115553
4            Reason_type_4     0.839001
5   Transportation Expense     0.605284
6                      Age    -0.169891
7          Body Mass Index     0.279811
8                Education    -0.210533
9                 Children     0.348262
10                    Pets    -0.277396
11            Month Values     0.158930

# interpreting the coefficient

In [60]:
summary_table['odds_ratio'] = np.exp(summary_table.coefficient)

In [61]:
summary_table

Feature name  coefficient  odds_ratio
0                Intercept    -1.647455    0.192539
1            Reason_type_1     2.800197   16.447892
2            Reason_type_2     0.951884    2.590585
3            Reason_type_3     3.115553   22.545903
4            Reason_type_4     0.839001    2.314054
5   Transportation Expense     0.605284    1.831773
6                      Age    -0.169891    0.843757
7          Body Mass Index     0.279811    1.322880
8                Education    -0.210533    0.810152
9                 Children     0.348262    1.416604
10                    Pets    -0.277396    0.757754
11            Month Values     0.158930    1.172256

In [62]:
summary_table.sort_values('odds_ratio',ascending=False)

Feature name  coefficient  odds_ratio
3            Reason_type_3     3.115553   22.545903
1            Reason_type_1     2.800197   16.447892
2            Reason_type_2     0.951884    2.590585
4            Reason_type_4     0.839001    2.314054
5   Transportation Expense     0.605284    1.831773
9                 Children     0.348262    1.416604
7          Body Mass Index     0.279811    1.322880
11            Month Values     0.158930    1.172256
6                      Age    -0.169891    0.843757
8                Education    -0.210533    0.810152
10                    Pets    -0.277396    0.757754
0                Intercept    -1.647455    0.192539

# testing the model

In [63]:
reg.score(x_test,y_test)

0.75

In [64]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.71340413, 0.28659587],
       [0.58724228, 0.41275772],
       [0.44020821, 0.55979179],
       [0.78159464, 0.21840536],
       [0.08410854, 0.91589146],
       [0.33487603, 0.66512397],
       [0.29984576, 0.70015424],
       [0.13103971, 0.86896029],
       [0.78625404, 0.21374596],
       [0.74903632, 0.25096368],
       [0.49397598, 0.50602402],
       [0.22484913, 0.77515087],
       [0.07129151, 0.92870849],
       [0.73178133, 0.26821867],
       [0.30934135, 0.69065865],
       [0.5471671 , 0.4528329 ],
       [0.55052275, 0.44947725],
       [0.5392707 , 0.4607293 ],
       [0.40201117, 0.59798883],
       [0.05361575, 0.94638425],
       [0.7003009 , 0.2996991 ],
       [0.78159464, 0.21840536],
       [0.42037128, 0.57962872],
       [0.42037128, 0.57962872],
       [0.24783565, 0.75216435],
       [0.74566259, 0.25433741],
       [0.51017274, 0.48982726],
       [0.85690195, 0.14309805],
       [0.20349733, 0.79650267],
       [0.78159464, 0.21840536],
       [0.

In [65]:
predicted_proba.shape

(140, 2)

In [66]:
predicted_proba[:,1]

array([0.28659587, 0.41275772, 0.55979179, 0.21840536, 0.91589146,
       0.66512397, 0.70015424, 0.86896029, 0.21374596, 0.25096368,
       0.50602402, 0.77515087, 0.92870849, 0.26821867, 0.69065865,
       0.4528329 , 0.44947725, 0.4607293 , 0.59798883, 0.94638425,
       0.2996991 , 0.21840536, 0.57962872, 0.57962872, 0.75216435,
       0.25433741, 0.48982726, 0.14309805, 0.79650267, 0.21840536,
       0.36956558, 0.67906035, 0.68502567, 0.52868083, 0.21840536,
       0.53506551, 0.22147081, 0.73692105, 0.40498044, 0.60505988,
       0.21075848, 0.45224466, 0.23751292, 0.39833498, 0.82755447,
       0.56797575, 0.69113325, 0.28659587, 0.21935267, 0.2033097 ,
       0.57628256, 0.3294664 , 0.66512397, 0.26949499, 0.83321968,
       0.43491525, 0.88374612, 0.23127072, 0.33415858, 0.34432939,
       0.69909345, 0.65494263, 0.29244941, 0.79200758, 0.20750276,
       0.26840558, 0.08708566, 0.22147081, 0.73245417, 0.30530219,
       0.22147081, 0.29014408, 0.90438191, 0.46061297, 0.60174

# save the model

In [67]:
import pickle

In [68]:
with open('model','wb')as file:
    pickle.dump(reg,file)

In [69]:
with open('scaler','wb')as file:
    pickle.dump(absenteeism_scaler,file)